/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;
import Modelos.Conexao;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.nio.charset.Charset;
import java.sql.*;
import javax.swing.border.LineBorder;
import org.json.JSONObject;

/**
 *
 * @author sucel
 */
public class CadastrarQuiroprata extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastrarQuiroprata
     */
    public CadastrarQuiroprata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeQuiroprata = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cpfQuiroprata = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        dataNascQuiroprata = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        sexoQuiroprata = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        logradouroQuiroprata = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        numeroQuiroprata = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bairroQuiroprata = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cidadeQuiroprata = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ufQuiroprata = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        complQuiroprata = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cepQuiroprata = new javax.swing.JFormattedTextField();
        telefone1Quiroprata = new javax.swing.JFormattedTextField();
        telefone2Quiroprata = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        botaoSalvarQuiroprata = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastrar Quiroprata");
        setPreferredSize(new java.awt.Dimension(1296, 620));

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(1250, 500));

        jPanel3.setBackground(new java.awt.Color(51, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12))); // NOI18N

        jLabel1.setText("Nome do Quiroprata: ");

        nomeQuiroprata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeQuiroprataActionPerformed(evt);
            }
        });

        jLabel2.setText("CPF:");

        try {
            cpfQuiroprata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfQuiroprata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cpfQuiroprataKeyReleased(evt);
            }
        });

        jLabel3.setText("Data Nascimento:");

        try {
            dataNascQuiroprata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel11.setText("Sexo");

        sexoQuiroprata.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino", " " }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpfQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataNascQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexoQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cpfQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dataNascQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(sexoQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Localização/Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12))); // NOI18N

        jLabel5.setText("CEP:");

        jLabel7.setText("Logradouro:");

        logradouroQuiroprata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logradouroQuiroprataActionPerformed(evt);
            }
        });

        jLabel8.setText("Número:");

        numeroQuiroprata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroQuiroprataActionPerformed(evt);
            }
        });

        jLabel6.setText("Bairro:");

        jLabel9.setText("Cidade:");

        jLabel10.setText("UF:");

        jLabel12.setText("Complemento:");

        jLabel13.setText("Telefone 1: ");

        jLabel14.setText("Telefone 2: ");

        try {
            cepQuiroprata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cepQuiroprata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepQuiroprataActionPerformed(evt);
            }
        });
        cepQuiroprata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cepQuiroprataKeyReleased(evt);
            }
        });

        try {
            telefone1Quiroprata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefone1Quiroprata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefone1QuiroprataActionPerformed(evt);
            }
        });

        try {
            telefone2Quiroprata.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefone2Quiroprata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefone2QuiroprataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(26, 26, 26)
                        .addComponent(telefone1Quiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefone2Quiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(logradouroQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cepQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bairroQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numeroQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cidadeQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ufQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(complQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cepQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(logradouroQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(bairroQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cidadeQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(ufQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(numeroQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(complQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(telefone1Quiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefone2Quiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/raioxcoluna.png"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/raioxcoluna.png"))); // NOI18N

        botaoSalvarQuiroprata.setBackground(new java.awt.Color(102, 153, 0));
        botaoSalvarQuiroprata.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        botaoSalvarQuiroprata.setText("Salvar");
        botaoSalvarQuiroprata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarQuiroprataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(botaoSalvarQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(351, 351, 351)))))
                .addComponent(jLabel16)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(125, 125, 125))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoSalvarQuiroprata, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeQuiroprataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeQuiroprataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeQuiroprataActionPerformed

    private void numeroQuiroprataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroQuiroprataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroQuiroprataActionPerformed

    private void telefone1QuiroprataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefone1QuiroprataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefone1QuiroprataActionPerformed

    private void telefone2QuiroprataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefone2QuiroprataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefone2QuiroprataActionPerformed

    private void botaoSalvarQuiroprataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarQuiroprataActionPerformed
   
            String msg = "";
            if(nomeQuiroprata.getText().equals("")) {
                msg += "Favor preencher campo nome do Quiroprata;\n";
            }
            if(cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().isEmpty()) {
                msg += "Favor preencher campo CPF;\n";

            }
            if(dataNascQuiroprata.getText().replaceAll("\\/","").trim().isEmpty()){
                msg += "Favor preencher campo Data Nascimento;\n";
            }
            if(sexoQuiroprata.getSelectedItem().equals("Selecione")) {
                msg += "Favor selecionar campo Sexo;\n";
            }
            if(telefone1Quiroprata.getText().replaceAll("\\(", "").replaceAll("\\)", "").replaceAll("\\-","").trim().isEmpty()){
                msg += "Favor preencher Telefone 1.\n";
            }
            if(!msg.equals("")){
                JOptionPane.showMessageDialog(null, msg);
                return;
            }
            
            //instancia a conexao com o banco de dados
            Conexao com = new Conexao();
            Statement stmt = null;
            
            try{
               stmt = com.c.createStatement();
               
               stmt.executeUpdate("INSERT INTO Quiroprata (Nome, CPF, DataNasc, Sexo, CEP, Logradouro, Bairro, Cidade, UF, Numero, Complemento, Telefone1, Telefone2) VALUES ('"+nomeQuiroprata.getText()+"','"+cpfQuiroprata.getText()+"','"+dataNascQuiroprata.getText()+"','"+sexoQuiroprata.getSelectedItem()+"','"+cepQuiroprata.getText()+"','"+logradouroQuiroprata.getText()+"','"+bairroQuiroprata.getText()+"','"+cidadeQuiroprata.getText()+"','"+ufQuiroprata.getText()+"','"+numeroQuiroprata.getText()+"','"+complQuiroprata.getText()+"','"+telefone1Quiroprata.getText()+"','"+telefone2Quiroprata.getText()+"')");
               
               stmt.close();
               
               com.c.close();
               
               JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
               nomeQuiroprata.setText("");
               cpfQuiroprata.setText("");
               dataNascQuiroprata.setText("");
               sexoQuiroprata.setSelectedItem("Selecione");
               cepQuiroprata.setText("");
               logradouroQuiroprata.setText("");
               bairroQuiroprata.setText("");
               cidadeQuiroprata.setText("");
               ufQuiroprata.setText("");
               numeroQuiroprata.setText("");
               complQuiroprata.setText("");
               telefone1Quiroprata.setText("");
               telefone2Quiroprata.setText("");
            } catch ( Exception e ) {
                System.err.println( e.getClass().getName() + ": " + e.getMessage() );
                System.exit(0);
            }
    }//GEN-LAST:event_botaoSalvarQuiroprataActionPerformed

    private void cepQuiroprataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cepQuiroprataKeyReleased
        if(cepQuiroprata.getText().trim().length() < 9) {
            logradouroQuiroprata.setText("");
            bairroQuiroprata.setText("");
            cidadeQuiroprata.setText("");
            ufQuiroprata.setText("");
        }
        if(cepQuiroprata.getText().trim().length() == 9) {
            try {
            String aUrl = "http://viacep.com.br/ws/" + cepQuiroprata.getText() + "/json/";
            URL url = new URL(aUrl);
            URLConnection req;
            req = url.openConnection();
            req.connect();
            InputStream is = (InputStream) req.getContent();
            BufferedReader rd = new BufferedReader(new InputStreamReader(is, Charset.forName("UTF-8")));
            String json;
            StringBuilder content = new StringBuilder();
            while ((json = rd.readLine()) != null)
            content.append(json + "\n");
            rd.close();
            //Instanciamos a classe que vai transformar o json em um Objeto
            JSONObject jsonOb = new JSONObject(content.toString());
            if (jsonOb.has("erro")) { // has = tem (Pergunta: no jsonOb TEM umA chave que mostra erro?)
                JOptionPane.showMessageDialog(null, "O CEP digitado é invalido!");
            }else {
                //inserindo o nome da rua na label jLabel1
                logradouroQuiroprata.setText(jsonOb.get("logradouro").toString());
                //inserindo o bairro na label jLabel2
                bairroQuiroprata.setText(jsonOb.get("bairro").toString());
                cidadeQuiroprata.setText(jsonOb.get("localidade").toString());
                ufQuiroprata.setText(jsonOb.get("uf").toString());
            }
            
        } catch (MalformedURLException ex) {
            java.util.logging.Logger.getLogger(CadastrarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(CadastrarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        }
        
    }//GEN-LAST:event_cepQuiroprataKeyReleased

    private void logradouroQuiroprataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logradouroQuiroprataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logradouroQuiroprataActionPerformed

    private void cepQuiroprataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepQuiroprataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cepQuiroprataActionPerformed

    private void cpfQuiroprataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpfQuiroprataKeyReleased
         if (cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().isEmpty()) {
            cpfQuiroprata.setBorder(new LineBorder(Color.BLACK));
        } else if (cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().length() >= 1 && cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().length() <= 10 || cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().length() != 11) {
            cpfQuiroprata.setBorder(new LineBorder(Color.RED));
        } else {
            int numero_01 = Integer.parseInt (cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().substring(0, 1));  
            int numero_02 = Integer.parseInt (cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().substring(1, 2));  
            int numero_03 = Integer.parseInt (cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().substring(2, 3));  
            int numero_04 = Integer.parseInt (cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().substring(3, 4));  
            int numero_05 = Integer.parseInt (cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().substring(4, 5));  
            int numero_06 = Integer.parseInt (cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().substring(5 ,6));  
            int numero_07 = Integer.parseInt (cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().substring(6, 7));  
            int numero_08 = Integer.parseInt (cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().substring(7, 8));  
            int numero_09 = Integer.parseInt (cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().substring(8, 9));  
            int numero_10 = Integer.parseInt (cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().substring(9, 10));  
            int numero_11 = Integer.parseInt (cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().substring(10, 11));  

            int digito_01_numero_01 = numero_01 * 10;
            int digito_01_numero_02 = numero_02 * 9;
            int digito_01_numero_03 = numero_03 * 8;
            int digito_01_numero_04 = numero_04 * 7;
            int digito_01_numero_05 = numero_05 * 6;
            int digito_01_numero_06 = numero_06 * 5;
            int digito_01_numero_07 = numero_07 * 4;
            int digito_01_numero_08 = numero_08 * 3;
            int digito_01_numero_09 = numero_09 * 2;

            int soma_01 = digito_01_numero_01 + digito_01_numero_02 + digito_01_numero_03 + digito_01_numero_04 + digito_01_numero_05 + digito_01_numero_06 + digito_01_numero_07 + digito_01_numero_08 + digito_01_numero_09;

            int digito_01 = soma_01 % 11;

            if (digito_01 < 2) {
                digito_01 = 0;
            } else {
                digito_01 = 11 - digito_01;
            }
            //System.out.println (digito_01);

            int digito_02_numero_01 = numero_01 * 11;
            int digito_02_numero_02 = numero_02 * 10;
            int digito_02_numero_03 = numero_03 * 9;
            int digito_02_numero_04 = numero_04 * 8;
            int digito_02_numero_05 = numero_05 * 7;
            int digito_02_numero_06 = numero_06 * 6;
            int digito_02_numero_07 = numero_07 * 5;
            int digito_02_numero_08 = numero_08 * 4;
            int digito_02_numero_09 = numero_09 * 3;
            int digito_02_numero_10 = numero_10 * 2;

            int soma_02 = digito_02_numero_01 + digito_02_numero_02 + digito_02_numero_03 + digito_02_numero_04 + digito_02_numero_05 + digito_02_numero_06 + digito_02_numero_07 + digito_02_numero_08 + digito_02_numero_09 + digito_02_numero_10;

            int digito_02 = soma_02 % 11;

            if (digito_02 < 2) {
                digito_02 = 0;
            } else {
                digito_02 = 11 - digito_02;	
            }
            //System.out.println (digito_02);

            if (numero_10 != digito_01 || numero_11 != digito_02 || cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().equals("11111111111")  || cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().equals("22222222222") || cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().equals("33333333333") || cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().equals("44444444444") || cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().equals("55555555555") || cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().equals("66666666666") || cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().equals("77777777777") || cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().equals("88888888888") || cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().equals("99999999999") || cpfQuiroprata.getText().replaceAll("\\.", "").replaceAll("-", "").trim().equals("00000000000")) {
                
                JOptionPane.showMessageDialog (null, "Número de CPF inválido, por favor insira um novo", "CPF inválido", JOptionPane.ERROR_MESSAGE);
                cpfQuiroprata.setBorder(new LineBorder(Color.RED));
                
                cpfQuiroprata.setText("");
            } else {
                //JOptionPane.showMessageDialog (null, "Número de CPF " + txtCPF + " foi válidado. Número de CPF correto", "CPF válido", JOptionPane.INFORMATION_MESSAGE);
                cpfQuiroprata.setBorder(new LineBorder(Color.GREEN));
                
            }
        }
    }//GEN-LAST:event_cpfQuiroprataKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairroQuiroprata;
    private javax.swing.JButton botaoSalvarQuiroprata;
    private javax.swing.JFormattedTextField cepQuiroprata;
    private javax.swing.JTextField cidadeQuiroprata;
    private javax.swing.JTextField complQuiroprata;
    private javax.swing.JFormattedTextField cpfQuiroprata;
    private javax.swing.JFormattedTextField dataNascQuiroprata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField logradouroQuiroprata;
    private javax.swing.JTextField nomeQuiroprata;
    private javax.swing.JTextField numeroQuiroprata;
    private javax.swing.JComboBox<String> sexoQuiroprata;
    private javax.swing.JFormattedTextField telefone1Quiroprata;
    private javax.swing.JFormattedTextField telefone2Quiroprata;
    private javax.swing.JTextField ufQuiroprata;
    // End of variables declaration//GEN-END:variables
}
